# This file was generated by GoReleaser. DO NOT EDIT.
cask "tunr" do
  name "tunr"
  desc "local → public tunnel tool for Vibecoders"
  homepage "https://tunr.sh"
  version "0.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tunr"

  on_macos do
    on_intel do
      url "https://github.com/tunr-dev/tunr/releases/download/v#{version}/tunr_#{version}_darwin_amd64.tar.gz"
      sha256 "87704209cd51ed893552bbe59f6481fe605ef657b3947088cd598dae594a8244"
    end
    on_arm do
      url "https://github.com/tunr-dev/tunr/releases/download/v#{version}/tunr_#{version}_darwin_arm64.tar.gz"
      sha256 "69f3cbef38f6e1c202b443458f12d44efa7380d44b94c300aa868d7094f5ca46"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tunr-dev/tunr/releases/download/v#{version}/tunr_#{version}_linux_amd64.tar.gz"
      sha256 "b54e9c32cf3358bf3b8e0986d27f2066682bc4f838f78e6aa5fa00bd68ba7b6a"
    end
    on_arm do
      url "https://github.com/tunr-dev/tunr/releases/download/v#{version}/tunr_#{version}_linux_arm64.tar.gz"
      sha256 "6da5e67ef73b66b7b76e4d10f067330e346b54d42c7f336e484f070d1b656794"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tunr"]
    end
  end

  # No zap stanza required
end
