# This file was generated by GoReleaser. DO NOT EDIT.
cask "tunr" do
  name "tunr"
  desc "local → public tunnel tool for Vibecoders"
  homepage "https://tunr.sh"
  version "0.6.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tunr"

  on_macos do
    on_intel do
      url "https://github.com/tunr-dev/tunr/releases/download/v#{version}/tunr_#{version}_darwin_amd64.tar.gz"
      sha256 "5200f25ce3470b2bf359c0ad8247ea0d6b2f465de5981ee5ec39b9fa583bb75a"
    end
    on_arm do
      url "https://github.com/tunr-dev/tunr/releases/download/v#{version}/tunr_#{version}_darwin_arm64.tar.gz"
      sha256 "a29e0b34e44bde68f7ac1ffc88b747d020903deba7befc1791addfaeee2d10b7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tunr-dev/tunr/releases/download/v#{version}/tunr_#{version}_linux_amd64.tar.gz"
      sha256 "76405f0a7ace7f4383f8b91a9b452f44e2de896c6b8486a7ed55f74409b2d84b"
    end
    on_arm do
      url "https://github.com/tunr-dev/tunr/releases/download/v#{version}/tunr_#{version}_linux_arm64.tar.gz"
      sha256 "3a1f410e946576e96c9783941437e94703b950e255ba23d1bcf884bad27a9a13"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tunr"]
    end
  end

  # No zap stanza required
end
